version: 2

models:
  - name: stg_strava_activities
    description: Staging table for activities
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null