version: 2

models:
  - name: stg_activities
    description: Staging table for activities
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: sport
        description: '{{ doc("activity_type") }}'
        tests:
          - accepted_values:
              values:
                - Run
                - Ride
                - Rowing
                - Hike
  - name: stg_activity_laps
    description: Staging table for activity laps
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: activity_id
        description: Foreign key for activity.id
        tests:
          - relationships:
              to: ref('stg_activities')
              field: id
  - name: stg_activity_zones
    description: Staging table for activity zones
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: activity_id
        description: Foreign key for activity.id
        tests:
          - relationships:
              to: ref('stg_activities')
              field: id
      - name: type
        description: '{{ doc("activity_zone_type") }}'
        tests:
          - accepted_values:
              values:
                - power
                - heartrate
                - pace