version: 2

models:
  - name: stg_strava_activities
    description: Staging table for activities
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_strava_activity_zones
    description: Staging table for activity zones
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: activity_id
        description: Foreign key for stg_strava_activities.id
        tests:
          - not_null
      - name: zone_type_name
        description: '{{ doc("activity_zone_type_name") }}'
        tests:
          - accepted_values:
              values:
                - Heartrate
                - Pace
                - Power