version: 2

sources:
  - name: strava_dev
    database: strava-exploration-v2
    schema: strava_dev
    description: Development BQ schema for strava-api v2
    tables:
      - name: activities
        description: Source table for /athlete/activities endpoint
        loaded_at_field: CAST(last_updated AS TIMESTAMP)
        freshness:
          warn_after: 
            count: 7
            period: day
      - name: activity_laps
        description: Source table for /activities/{id}/laps endpoint
        loaded_at_field: CAST(last_updated AS TIMESTAMP)
        freshness:
          warn_after: 
            count: 7
            period: day
      - name: activity_zones
        description: Source table for /activities/{id}/zones endpoint
        loaded_at_field: CAST(last_updated AS TIMESTAMP)
        freshness:
          warn_after: 
            count: 7
            period: day